# Generated by Django 2.1.5 on 2020-01-26 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cyclone',
            fields=[
                ('sid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CycloneNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_index', models.IntegerField()),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
                ('intensity', models.IntegerField(null=True)),
                ('cyclone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='cycloneapp.Cyclone')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cyclonenode',
            unique_together={('time_index', 'cyclone')},
        ),
    ]
