# Generated by Django 2.1.5 on 2020-01-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cyclone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('long', models.IntegerField()),
                ('lat', models.IntegerField()),
                ('intensity', models.IntegerField()),
            ],
        ),
    ]
