# Generated by Django 2.1.5 on 2020-01-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycloneapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclone',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
